# Generated by Django 4.1.13 on 2025-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/faculty/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/students/'),
        ),
    ]
