# Generated by Django 4.1.13 on 2025-01-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AttendanceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_confirmed', models.BooleanField(default=False)),
                ('confirmation_time', models.DateTimeField(null=True)),
                ('dispute_raised', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.attendance')),
            ],
        ),
    ]
