# Generated by Django 4.1.13 on 2025-01-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('faculty', 'day', 'time_slot')},
        ),
    ]
