# Generated by Django 4.2 on 2025-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancealert',
            name='attendance_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='requires_facial_verification',
            field=models.BooleanField(default=True),
        ),
    ]
